# Fandemonium {#turning-fantasy-draft-chaos-into-cash}

#### Keywords

fantasy sports, fantasy draft, daily fantasy, machine learning, predictive analytics

## Evaluate the Fantasy Landscape

The object of the typical daily fantasy league is simple: given a set salary, draft the best possible roster and hope that your team scores more points than your opponents' teams to win cash. The process seems easy enough for the 41.5 million people who give it a shot each year[^1]. Every time that football season approaches, radio and TV channels fill up with ads claiming giant winnings for 24 hours worth of commitment. Draftkings boasts "a new fantasy millionaire every week"[^2], but the reality is that 89.3% of their players lost money across the 2013 and 2014 seasons[^3]. In reality, the people who come out on top spend hours researching upcoming games, relationships between players, and underpriced prospects just to end up with a positive return on their investment. These lucky people do well; just 1% of players earn 91% of the overall winnings[^4]. How can the average sports fan, with a full time job and a life outside of sports research, possibly come out on top?

## Finalize your Lineup

Fandemonium is the layman's answer to the chaos and risk (?) of the daily fantasy trade. Fandemonium is a Vegas bookie in your pocket: an artificial intelligence-enhanced mobile and web app that harnesses the power of predictive analytics to analyze the roster of available players for a given sport, salary per player, current and projected stats, current injuries, upcoming games, and more to suggest the draft lineup likely to earn the most points and win you money. Not into football? Fandemonium prepares recommended rosters for basketball and baseball as well. Have a favorite player that just HAS to be on your roster? You can "lock in" any number of players first, and Fandemonium will recommend the best combination of players to fill the remaining spots on your roster. With Fandemonium, you don't need to quit your job _and_ study sports analytics full time just to turn a profit - you can let the AI do the math, crunch the numbers, and pick your team for you. 

## Turn Chaos into Cash

Fandemonium pays for itself the first time you use its expert advice to set your lineup and get a taste of that cash win. On average, Fandemonium users win 10% more often and 20% more cash in a given season than daily fantasy players who do not use our advanced technology. It is worth noting that our application is not magic, and so even its expert recommendations will not be 100% accurate with every prediction. The version of Fandemonium currently available is specifically designed for daily fantasy leagues and does not support season-long draft contests or rotisserie-style drafts. Future releases of the app will support soccer, golf, and hockey daily leagues.

## Bibliography
[^1]: https://fantasy-sport.net/fanduel-vs-draftkings/  
[^2]: http://www.preventionlane.org/draftkings-espn-football  
[^3]: https://splinternews.com/the-percentage-of-players-who-lose-at-daily-fantasy-spo-1793853043  
[^4]: http://www.dailyherald.com/article/20151012/business/151019683/  
